# INTRODUCTION {#ref-intro}

The sustainable management of marine fisheries has been recognized as a critical challenge to address in the 21^st^ century [@cbdAichiBiodiversityTargets2018]. Achieving sustainability goals requires an understanding of complex ecological, socio-economic, and political factors and their interactions [@halpernAchievingTripleBottom2013]. For example, fisheries management regions were often delineated as a result of political or geographic considerations rather than biological or ecological rationale. As a result, defined management areas for a species often either encompass a region in which environmental conditions and life-history traits are highly variable or only include a subset of the population [@cadrinDefiningSpatialStructure2020a]. Both of these scenarios are challenging for traditional assessment techniques that assume closed populations along with homogeneous environments and life-history traits [@hilbornQuantitativeFisheriesStock1992]. 

Accounting for spatially and temporally variable processes has long been recognized as a challenge in fisheries science [@bevertonDynamicsExploitedFish1957; @hilbornQuantitativeFisheriesStock1992; @rickerFurtherNotesFishing1944]. Many traditional fisheries methods that are still operationalized today require assumptions about underlying spatial processes; these assumptions generally result in models that treat stocks as spatially homogeneous entities [@bevertonDynamicsExploitedFish1957; @rickerComputationInterpretationBiological1975; @hilbornQuantitativeFisheriesStock1992]. These simplifications were necessary because of computational and statistical limitations and techniques, such as survey stratification, that were implemented to account for spatial heterogeneity and reduce uncertainty in the indices feeding these models [@smithAnalysisDataBottom1996]. Due in part to the lack of spatial context provided by traditional stock assessments, indices were developed to quantify changes in spatial patterns [e.g. @reuchlin-hugenholtzPotentialSpatialDistribution2015]. These indices are an additional source of information for assessing stock health, and while they describe how distributions (e.g. abundance or biomass) have changed over time they are unable to provide a detailed understanding of the spatial changes in these distributions.

Species distribution models (SDMs) were one of the earliest modeling frameworks developed to better understand how environmental factors influenced the distribution of a population [@grinnellOriginDistributionChestNutBacked1904; @boxPredictingPhysiognomicVegetation1981; @boothBioclimFirstSpecies2014]. These models combine environmental data and species' ecological information to map the occurrence probability (OP; or some measure of abundance) of a species across some land(sea)-scape [@boxPredictingPhysiognomicVegetation1981]. In the marine realm, the influence of SDMs has increased rapidly in recent years; SDMs have been used in the development of Marine Protected Areas (MPAs) and MPA networks, to better understand the distribution of Species at Risk (SAR), and to predict the impact of climate change [@cheungApplicationMacroecologicalTheory2008; @robinsonPushingLimitsMarine2011; @sundbladEcologicalCoherenceMarine2011; @domischSpatiallyExplicitSpecies2019; @mchenryProjectingMarineSpecies2019].

Historically, SDMs often did not explicitly consider temporal changes in the relationship between the environment and the response of the species; these SDMs provided a snapshot in time based on available data [@elithSpeciesDistributionModels2009]. However, more sophisticated SDM frameworks have been developed that allow the underlying relationships to vary in time and space. This has led to dynamic models that better utilize the latent spatio-temporal information contained in the data [@merowDevelopingDynamicMechanistic2011; @thorsonJointDynamicSpecies2016; @martinez-minayaSpeciesDistributionModeling2018]. These new spatio-temporal SDMs were made possible by a number of recent statistical and computational advances such as the implementation of the Laplace approximation (LA), Automatic Differentiation (AD), Stochastic Partial Differential Equations (SPDE), and Gaussian Markov Random Fields (GMRFs) in commonly used programming languages [@kristensenTMBAutomaticDifferentiation2016; @rueBayesianComputingINLA2016; @thorsonGuidanceDecisionsUsing2019]. The complex spatio-temporal analytical problems associated with these advanced SDMs can now be solved in a fraction of the time required by traditional methods.

### Georges Bank

Georges Bank (GB) is home to a wealth of natural resources and for centuries has had some of the most productive fisheries in the world [@backusGeorgesBank1987]. In the 1960s and 1970s numerous countries conducted large unsustainable fisheries in the region, but with the introduction of Exclusive Economic Zones (EEZ) in 1977, control of resource exploitation (e.g. fisheries) fell under the jurisdiction of the United States (U.S.) and Canada [@hallidayNorthAtlanticFishery1996; @andersonHistoryFisheriesManagement1997]. The final demarcation of the Canadian and U.S. territorial waters on GB was implemented with an International Court of Justice (ICJ) decision in 1984. Within three years both countries had independent groundfish surveys covering the entirety of GB at different times of the year.

Historically, substantial groundfish fisheries occurred on GB, including Atlantic Cod (*Gadus morhua*) and Yellowtail Flounder (*Limanda ferruginea*) [@andersonHistoryFisheriesManagement1997]. As observed throughout the northwest Atlantic, the biomass of Atlantic Cod on GB declined significantly in the early 1990s and there has been little evidence for recovery of this stock since this collapse [@andrushchenkoAssessmentEasternGeorges2018]. Between the 1970s and the 1990s, the biomass of Yellowtail Flounder on GB was low, but evidence for a rapid recovery of this stock in the early 2000s resulted in directed fisheries for several years. However, this recovery was short lived and the biomass of this stock has been near historical lows for the last decade [@legaultStockAssessmentGeorges2018].

<!-- Fisheries management bodies in both Canada and the U.S. have implemented measures to protect the Atlantic Cod and Yellowtail Flounder stocks on GB. While these measures vary between the countries, there is a collaborative process to develop a shared quota for these two stocks [@tracTransboundaryResourceAssessment2020]; a quota which has declined substantially for both stocks over the last decade [@andrushchenkoAssessmentEasternGeorges2018; @legaultStockAssessmentGeorges2018]. In addition to regulations that attempt to directly limit fishing mortality, both countries have implemented spatial closures (Figure @ref(fig:Overview)). In the U.S., two large closed areas were implemented (Closed Area I (CA I) and II (CA II)) with the intent of aiding in the recovery of groundfish and invertebrate stocks on GB. These closures were established in 1994 and have been modified over time to occasionally allow some fishing activity [@linkEffectsAreaClosures2005; @murawskiLargescaleClosedAreas2000]. On the Canadian portion of GB, the groundfish fishery has historically been closed from March 1^st^ to May 31^st^ to protect spawning groundfish. In 1994 the closure was expanded to include the months of January and February in an effort to rebuild the Atlantic Haddock stock. This closure was subsequently shortened in 2005 to exclude January, resulting in a closure of the groundfish fishery from February through to the end of May. The Canadian Offshore Scallop Fishery (COSF) also faces restrictions on fishing during the peak groundfish spawning periods with time-area closures limiting the area in which this fishery can operate during February and March [Atlantic Cod; @dfoScallopFisheryArea2019] and June [Yellowtail Flounder; @dfoScallopFisheryArea2014]. The U.S. closures have been linked to the recovery of several stocks on GB [@linkEffectsAreaClosures2005; @murawskiLargescaleClosedAreas2000] although the reasons for the recent decline of Yellowtail Flounder and the ongoing lack of recovery of Atlantic Cod on the bank since the implementation of these closures remains uncertain [@andrushchenkoAssessmentEasternGeorges2018; @legaultStockAssessmentGeorges2018]. In Canada, there had been no comprehensive review of the closures until a recent review by @keithEvaluatingSocioeconomicConservation2020 that found little evidence that the COSF time-area closures were achieving their management objectives. This analysis also highlighted the need for a better understanding of the spatio-temporal distributions of both of these stocks in relation to the location and timing of these closures. -->

Here we use the R-INLA statistical framework [@lindgrenBayesianSpatialModelling2015; @rueBayesianComputingINLA2016; @bakkaSpatialModellingRINLA2018] to develop spatio-temporal SDMs for two depleted groundfish stocks on GB (Atlantic Cod and Yellowtail Flounder). Our objectives were to use data from three groundfish surveys in the region to: 1) develop temporally variable SDMs and explore the influence of a suite of static environmental layers, 2) identify any long-term shifts in the stock distributions, 3) identify any seasonal changes in the stock distributions using available survey data, and 4) use the SDMs to quantify any shifts in core area within Canadian and U.S. waters.

<!-- From a scientific perspective, disentangling how environmental, ecological, and anthropogenic factors impact the population dynamics of marine fishes is pivotal to development of sustainability strategies.  -->

<!-- Species Distribution models (SDMs) have been used for a long time in fisheries.  These models typically try to map spatial patterns in species distribution using available environmental covariates.  Without a detailed knowledge of processes underlying the spatial patterns the use of environmental covariates alone cannot fully account for spatial and temporal variability.  These environmental covariates are typically proxies for more complex unobserved(able)ed processes, and changes in these relationships are difficult to account for in these models. -->

<!-- Recent statistical advances have lead to the development of tools which can be used to develop more realistic SDMs.  These models can account for environmental covariates along with accounting for unexplained spatio-temporal variability.  These kindas of SDMs enable the model to identify the consistent environmental signal (covariates) to be estimated while also providing a statistical framework in which the unexplained spatio-temporal variability can be used to better understand spatio-temporal changes in the species distribution. -->

<!-- Tracking spatio-temporal changes facilitates the development of models which can identify consistent spatial anomalies in which the metric being measures deviates from expectation.  Tracking long-term changes improves our understanding of species shifts and provides insight into how changing environmental conditions impact the strength of the environmental correlations.  This provides a framework for predicting the impact of directed environmental change (e.g. climate change). -->
