# RESULTS {#ref-results}

## Distributional Shifts

For both stocks, the core areas (OP $\geq$ `r hi.prob`) shifted towards the north and east throughout the study period (Figure \@ref(fig:cog-hep)).  For Atlantic Cod, the shift in distribution of the core area occurred relatively rapidly in the 1990s and the centre of gravity (COG) of the core area has remained relatively stable since this period (Figure \@ref(fig:cog-hep)). In the 1970s and 1980s, core area was observed across the bank, however since the mid-1990s there was a clear shift in distribution with core area concentrated in the north-east portion of the bank, mainly in Canadian waters (see Supplemental Figures \@ref(fig:pf-winter-cod) -\@ref(fig:pf-fall-cod)). In addition, in the *Fall*, Atlantic Cod was distributed even further to the northeast along the edge of the study area. The size of the core area followed a similar temporal pattern, with a rapid decline in the core area for Atlantic Cod occurring in the 1990s in the *Winter* and *Spring* (Figure \@ref(fig:area-hep)). The decline in the size of the core area was observed approximately a decade earlier in the *Fall* and the size of the core area was always smaller in the *Fall* (Figure \@ref(fig:area-hep)). The distribution of Atlantic Cod along the edge of the bank during the *Fall* suggests that a substantial portion of this stock may have been located on the slope where survey coverage was limited (Figure \@ref(fig:Overview)).

The Yellowtail Flounder shift in COG (Figure \@ref(fig:cog-hep)), was largely the result of a reduction in the core area in the southwest portion of GB; the majority of core area was located in a central region of GB that straddles the ICJ line dividing Canada and the U.S. (Supplemental Figures \@ref(fig:pf-winter-yt) -\@ref(fig:pf-fall-yt)). The COG of Yellowtail Flounder has slowly been shifting towards the northeast (Figure \@ref(fig:area-hep)). The trends in the size of the core area during the *Spring* and *Fall* have been very similar with rapid declines in the early 1980s followed by an increase in the 1990s and early 2000s (Figure \@ref(fig:area-hep)). The size of the core area in the *Winter* has been in decline since a period of increase in the 1990s (Figure \@ref(fig:area-hep)).

For both stocks, the changes in the size of the core area were more pronounced in the U.S. than in Canadian waters (Figure \@ref(fig:area-can-vs-us-hep)). In the U.S., the declines in the size of core area of Atlantic Cod occurred rapidly in the early 1990s in the *Winter* and *Spring*. In the *Fall*, the loss of core area occurred approximately a decade earlier, although the size of the core area in the U.S. during the *Fall* was always substantially lower than in the *Winter* or *Spring*. In Canadian waters, there has been minimal change in the size of the core area for Atlantic Cod in any of the seasons through time; the size of the core area in the *Fall* has tended to be lower than observed in the *Winter* or *Spring* (Figure \@ref(fig:area-can-vs-us-hep)). For Yellowtail Flounder, the size of the core area in the U.S. declined steadily throughout the 1970s and 1980s, this was followed by an increase in the 1990s and early 2000s (Figure \@ref(fig:area-can-vs-us-hep)). Since the mid-2000s, the size of the core area in the U.S. appeared to stabilize. In Canadian waters, the size of core area for Yellowtail Flounder throughout the 1970s and 1980s was relatively low, slowly increased in the mid-1990s, and has been relatively stable since (Figure \@ref(fig:area-can-vs-us-hep)).

## Environmental Covariates

The spatial fields for the three environmental variables retained by model selection are shown in Supplemental Figure \@ref(fig:SST-Dep-Sed). The average SST between 1997 and 2008 had the largest effect on the OP of Atlantic Cod; they were more likely to be found in regions of the bank with a lower SST (Figure \@ref(fig:cod-fe)). For all 3 surveys, the OP of Atlantic Cod declined rapidly in regions of the bank where the SST was above approximately 10°C (Figure \@ref(fig:cod-fe)). Although depth was also retained in the final Atlantic Cod model, its effect on OP was substantially smaller than the SST effect. During the *Winter* and *Spring*, the OP peaked between `r c.dep.peak` m and declined slowly in shallower and deeper waters (Figure \@ref(fig:cod-fe)). There was no clear relationship with depth in the Winter.

For Yellowtail Flounder, depth had the largest effect on OP, with Yellowtail Flounder most likely to be observed between depths of `r yt.dep.peak` m in each of the 3 surveys and its effect on OP was highest during the *Spring* (Figure \@ref(fig:yt-fe)). The average SST between 1997 and 2008 was also included in the final model, with Yellowtail Flounder OP generally declining as SST increased. The effect of SST was least pronounced in the *Fall*. The sediment type also had a significant influence on the OP for Yellowtail Flounder in the *Winter* and *Fall*, with Sand and Gravel-Sand having higher OPs than the Other sediment category, this difference was most notable during the *Winter* (Figure \@ref(fig:yt-fe) and Supplemental Figure \@ref(fig:diag-3-fe)).

## Model Hyperparameters

The decorrelation range for Atlantic Cod was above 100 km throughout the year and was generally higher than that observed for Yellowtail Flounder (Figure \@ref(fig:hyper-range-var-est)). The range was highest for Atlantic Cod in the *Spring* with an estimate of `r range.spring.cod.mn.ci` km, while the range during the *Winter* spawning period was the lowest at `r range.winter.cod.mn.ci` km. In the *Fall*, the range declined from the *Spring*; this may indicate spatial contraction or fish leaving the study domain (Figure \@ref(fig:hyper-range-var-est)). For Yellowtail Flounder, the lowest range was estimated in the *Winter* at `r range.winter.yt.mn.ci` km with the *Spring* and *Fall* range estimates being higher and somewhat more variable than the *Winter* range estimate. The range estimates of Yellowtail Flounder throughout the year were smaller and less variable than that observed for Atlantic Cod (Figure \@ref(fig:hyper-range-var-est)). The uncertainty of these estimates precludes any statistical differences being observed between the seasons.

The standard deviation of the random field was lower for Atlantic Cod in the *Winter* and *Spring* than during the *Fall* (Figure \@ref(fig:hyper-sd-var-est)), this was indicative of the increased clustering of the stock and the relatively small effect of the environmental covariates in the *Fall*. The standard deviation of the random field was highest for Yellowtail Flounder in the *Winter* and the seasonal differences for Yellowtail Flounder were smaller than those observed with Atlantic Cod (Figure \@ref(fig:hyper-sd-var-est)). The standard deviation of the Yellowtail Flounder field was higher than Atlantic Cod in the *Winter* and *Spring*, but lower in the *Fall* (Figure \@ref(fig:hyper-sd-var-est)). The posteriors of other hyperparameters for both stocks in the *Winter*, *Spring*, and *Fall* are provided in Supplemental Figures \@ref(fig:hyper-cod-winter-post) - \@ref(fig:hyper-yt-fall-post).

## Validation and Prediction

The five fold cross validation indicated that each of the models tested (intercept only, SST (Atlantic Cod), Dep (Yellowtail Flounder), and Dep + SST) were able to predict the distribution for both stocks without an increase in bias or a loss of accuracy (Figure \@ref(fig:folds)). The mean error of the residuals for the validation training set predictions were similar to the error from the predicted test data and while the mean error of the test data was generally more variable, the estimates were centred on 0 and thus there was no evidence of bias in these predictions (Figure \@ref(fig:folds)). The RMSE from the test and training data showed similar patterns for both stocks and most models, although for Yellowtail Flounder the RMSE for both the training and test data from the intercept only model was slightly lower than either of the models with covariates. This indicates that the inclusion of the environmental covariates may result in a small loss of out-of-sample prediction (Figure \@ref(fig:folds)).

The error in the prediction of the distributions of each stock 1, 2, and 3 years into the future were well below the RMSE associated with a model with no predictive ability (dashed line; Figure \@ref(fig:pred-17-19)). The prediction for the models without any environmental covariates were similar to the prediction from the models that included both Dep and SST.  For both stocks, the 2018 data consistently had the lowest prediction accuracy with the models tending to predict individuals where none were observed. This was in agreement with observations of the survey biomass indices being near historic lows for both stocks in 2018 [@legaultStockAssessmentGeorges2018; @andrushchenkoAssessmentEasternGeorges2018]. Generally, the predictive error from these models were near the high end of the range of the annual model residual error, this indicates that these models were able to predict the spatial OP patterns for both stocks up to 3 years into the future without a substantial loss of accuracy, even with environmental covariates excluded from the models (Figure \@ref(fig:pred-17-19)).
